-- setup.sql
-- Configures initial requirements for the project SCHEMA
-- Run first
-- NOTE: USERNAME is hardcoded, change before running

-- Create a dedicated role for this project
CREATE ROLE IF NOT EXISTS dbt_role;

-- Grant necessary privileges to the role
GRANT ROLE dbt_role TO ROLE ACCOUNTADMIN;

-- Grant role to your user
GRANT ROLE dbt_role TO USER LILITMANUKYAN;

CREATE WAREHOUSE IF NOT EXISTS dbt_wh
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for manufacturing quality platform dbt project';

GRANT USAGE ON WAREHOUSE dbt_wh TO ROLE dbt_role;


CREATE DATABASE IF NOT EXISTS MANUFACTURING_QUALITY;

GRANT OWNERSHIP ON DATABASE MANUFACTURING_QUALITY TO ROLE dbt_role;


USE DATABASE MANUFACTURING_QUALITY;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS RAW_SYNTHETIC;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;

GRANT OWNERSHIP ON SCHEMA RAW            TO ROLE dbt_role;
GRANT OWNERSHIP ON SCHEMA RAW_SYNTHETIC  TO ROLE dbt_role;
GRANT OWNERSHIP ON SCHEMA STAGING        TO ROLE dbt_role;
GRANT OWNERSHIP ON SCHEMA INTERMEDIATE   TO ROLE dbt_role;
GRANT OWNERSHIP ON SCHEMA MARTS          TO ROLE dbt_role;


CREATE STAGE IF NOT EXISTS MANUFACTURING_QUALITY.RAW.manufacturing_raw_stage
    COMMENT = 'Internal stage for loading raw CSV files';

GRANT READ, WRITE ON STAGE MANUFACTURING_QUALITY.RAW.manufacturing_raw_stage TO ROLE dbt_role;


CREATE FILE FORMAT IF NOT EXISTS MANUFACTURING_QUALITY.RAW.manufacturing_csv_format
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_DELIMITER = ','
    DATE_FORMAT = 'YYYY-MM-DD'
    TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
    COMMENT = 'Standard CSV file format for manufacturing quality platform';

GRANT USAGE ON FILE FORMAT MANUFACTURING_QUALITY.RAW.manufacturing_csv_format TO ROLE dbt_role;

SHOW SCHEMAS IN DATABASE MANUFACTURING_QUALITY;
SHOW WAREHOUSES LIKE 'dbt_wh';
